---
  title: "CryptoCurrency Analysis"
output: html_notebook
---



```{r}
#installing the libraries
#tidyverse include packages such as dplvr, ggplot, purr

library(tidyverse)
library(lubridate)

#dygraphs provides rich facilities for charting time-series data in R

library(dygraphs)

#library for dygraph
library(xts)

#library for the correlation plot
library(corrplot)

```


```{r}
#Setting a directory with setwd() (The complete file path must be added)
"
setwd('C:/Users/jahna/Desktop/FILES/PROJECTS/Cryptocurrency/')

BTC_data <- read.csv(file = 'Data/bitcoin_dataset.csv', header = TRUE)

"

#Setting current directory of the file directly using file.path()

file_path = file.path('.', 'Data', 'bitcoin_dataset.csv')

#read_csv is from 'utils' library which is loaded on default

BTC_data <- read.csv(file = file_path, header = TRUE )
BTC_data
```
wegfhgj
```{r}
# Reading the Column

names(BTC_data)

#colnames(BTC_data)

#names & colnames are both same
```
```{r}

#Provides the stats of the dataset

summary(BTC_data)
str(BTC_data)

```

```{r}

#Date Column is of Class Character, so converting it into 
BTC_data$Date <- as.Date(BTC_data$Date)
BTC_data$Date
View(BTC_data)

``` 
```{r}

#function for plotting

feature_over_time <- function(data, feature_name){
  feature <- data %>% select(feature_name)
  feature_plot <- xts(feature, data$Date)
  
  dygraph(feature_plot, main = paste("Plot of ", feature_name)) %>% 
    dySeries(feature_name, label = feature_name) %>%  
    dyRangeSelector()
  
}
```

```{r}

#list of column names

names(BTC_data)
```

```{r}
#Analyzing the features over time i.e. Date

feature_over_time(BTC_data, names(BTC_data)[2])
feature_over_time(BTC_data, names(BTC_data)[3])
feature_over_time(BTC_data, names(BTC_data)[4])
feature_over_time(BTC_data, names(BTC_data)[5])
feature_over_time(BTC_data, names(BTC_data)[6])
feature_over_time(BTC_data, names(BTC_data)[7])
feature_over_time(BTC_data, names(BTC_data)[8])
feature_over_time(BTC_data, names(BTC_data)[9])
feature_over_time(BTC_data, names(BTC_data)[10])
feature_over_time(BTC_data, names(BTC_data)[11])
feature_over_time(BTC_data, names(BTC_data)[12])
feature_over_time(BTC_data, names(BTC_data)[13])
feature_over_time(BTC_data, names(BTC_data)[14])
feature_over_time(BTC_data, names(BTC_data)[15])
feature_over_time(BTC_data, names(BTC_data)[16])
feature_over_time(BTC_data, names(BTC_data)[17])
feature_over_time(BTC_data, names(BTC_data)[18])
feature_over_time(BTC_data, names(BTC_data)[19])
feature_over_time(BTC_data, names(BTC_data)[20])
feature_over_time(BTC_data, names(BTC_data)[21])
feature_over_time(BTC_data, names(BTC_data)[22])
feature_over_time(BTC_data, names(BTC_data)[23])
feature_over_time(BTC_data, names(BTC_data)[24])
```

```{r}
"
btc_rev <- cbind(BTC_data$btc_n_transactions, BTC_data$btc_n_transactions_total)
btc_rev_new <- xts(btc_rev, BTC_data$Date)
dygraph(btc_rev_new) %>% dyRangeSelector()
"
```

```{r}
#Intially btc_trade_volume has 21 "na" values and they are replaced by the mean of the coulmn

class(BTC_data$btc_trade_volume)
BTC_data$btc_trade_volume[is.na(BTC_data$btc_trade_volume)] <- round(mean(BTC_data$btc_trade_volume, na.rm = TRUE))
sum(is.na(BTC_data$btc_trade_volume))

```

```{r}
plot_BTC <- cor(BTC_data[c(2:24)])
corrplot(plot_BTC, method = "ellipse", tl.srt = 90, tl.col = "black", tl.cex = 0.54, title = "Correlation of Variables", mar=c(0,0,1,0))

"
from the graph it can be seen that the features 
* btc_market_cap
* btc_miners_revenue
* btc_estimated_transaction_volume_usd
* btc_hash_rate
* btc_difficulty
* btc_trade_volume
"

```
```{r}
help("corrplot")

```

